name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Run Your Script
      run: |
        # Replace this with the actual command or script you want to run
        echo "This is a simple action for pull requests"
